name: Test automation workflow

on:
  schedule:
  - cron: 30 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running test automation framework with maven
      run: mvn clean test -Dbrowser=firefox -DisLamdaTest=false -DisHeadless=true

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test logs
        path: logs/
        
    - name: Upload Test reports
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test report
        path: report.html/

    - name: Test execution status
      run: echo "Test execution completed"


  
