name: Test automation workflow

on:
  schedule:
  - cron: 30 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running test automation framework with maven
      run: mvn clean test -Dbrowser=firefox -DisLamdaTest=false -DisHeadless=true

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test logs
        path: logs/
        
    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: screenShoots
        path: screenShoots/

    - name: Upload HTML Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: html-report
        path: reports/report.html

    - name: Test execution status
      run: echo "Test execution completed"

    - name: Copy Report to gh-pages Folder
      if: always()
      run: |
        mkdir -p public/extent-reports/screenShoots
        cp reports/report.html public/extent-reports/index.html
        cp -R screenShoots/* public/extent-reports/screenShoots/
        ls -l public/extent-reports

    - name: Deploy 🚀
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages                 # default publishing branch
        folder: public/extent-reports   # folder to publish
        token: ${{ secrets.PAT001 }}
        clean: true



  
